server:
  #可修改此处项目启动端口号启动多个项目,测试伪分布式的登陆,分发等方案
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 200
  tomcat.uri-encoding: UTF-8

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/aaa?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 3
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        filters: stat,wall,slf4j
        name: 123
    thymeleaf:
      cache: false
    session:
      store-type: redis


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.saas.admin.model
  
logging:
  level:
    com:
      shrek:
        supervisor: 
          dao: debug
          
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

platform:
      name: saas